services:
  app:
    build: .
    ports:
      - '3030:3030'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/fintech-system?replicaSet=rs0
    depends_on:
      - mongo
      - mongo-init
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:prod

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
      sleep 5 &&
      mongosh --host mongo --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [{ _id: 0, host: \"mongo:27017\" }]
        })'"
    restart: 'no'

volumes:
  mongo-data:
